### ISSUE TITLE
How to set pdfscribe as default printer

### ISSUE THREAD

**Issue by shashankSkydale** [stchan/PdfScribe#21]
Hi,
I need guidance on how to set pdfscribe as default printer during installation of pdfscribe.

**Comment by stchan** [comment]
Since you won't take any polite hints, I'm going to just say this directly - I am not doing your research for you, and I am not debugging any of your customizations. Cut the crap - you've already been told nobody's doing your homework for you, and I see you've opened one line issues on other repositories simply expecting people to fix your local issues with no documentation of any efforts you may have made. Stop trying to get me to do your work for you - this is your only warning - any more and you're going to be blocked.
