### ISSUE TITLE
Some compatibility errors

### ISSUE THREAD

**Issue by Lightbxx** [stchan/PdfScribe#46]
Dear Stchan,
I printed a PDF in Windows7. The printed document has an error as shown in the figure below, which seems to be a postscript compatibility problem. Can you tell me how to solve this problem.THX.

![error](https://user-images.githubusercontent.com/88480281/203559492-5e507b1d-13a6-4d6e-b101-ed131f93db4e.png)

**Comment by stchan** [comment]
This could be caused by printing a secured PDF with Acrobat reader, this will happen (the reader will write a warning message into the postscript that ghostscript trips up on). This is a long known issue that would require parsing the postscript to remove the text causing the problem. A workaround is to print the PDF from a third party reader (like FoxIt).

If that's not what caused it, you could try looking at the postscript before it gets sent to PdfScribe.exe (either change the code to save it, or change the port configuration to ask for a filename rather than directing it to pdfscribe.exe)

**Comment by stchan** [comment]
[Prerelease v.1.2.1](https://github.com/stchan/PdfScribe/releases/tag/v1.2.1_prerelease) is a fix for #33/#25 - if this issue is related, it should fix it as well.

**Comment by stchan** [comment]
closing due to iinactivity
