### ISSUE TITLE
Support for 32bit processor

### ISSUE THREAD

**Issue by thieuquangcuong** [stchan/PdfScribe#5]
Hi,

I really appreciated for what you have done for this project. That helps me a lot for my currently project. But, now I'm facing a challenge with the 32bit processor because the dll which included in this project is not supported for 32bit.
Is there any way I can change the project to supports 32bit processor? 

Huge thanks.

**Comment by cedrozor** [comment]
I use pdf scribe in my project (https://github.com/cedrozor/myrtille) in both 32 and 64 bits (auto-detected), if you want to have a look (https://github.com/cedrozor/myrtille/search?p=1&q=pdfscribe&unscoped_q=pdfscribe)

**Comment by thieuquangcuong** [comment]
> I use pdf scribe in my project (https://github.com/cedrozor/myrtille) in both 32 and 64 bits (auto-detected), if you want to have a look (https://github.com/cedrozor/myrtille/search?p=1&q=pdfscribe&unscoped_q=pdfscribe)

You save my day, thanks alot!

**Comment by stchan** [comment]
Closing this as cedrozor has offered his fork as a solution, and I do not plan to support a 32-bit release.

**Comment by kisskumam** [comment]
@cedrozor @stchan  @thieuquangcuong  I'm facing a problem with install package for 32bits processor also. Currently, I'm using Wix to build the x86 package. I have tried to install on some windows 7 computers and only one can successfully installed. 

The other performed a rollback after install then show this message: Setup wizard ended prematurely because of an error. your system has not been modified.

Do you guys have ever got this same problem as mine? Please helps!

**Comment by kisskumam** [comment]
[https://drive.google.com/open?id=1Hgi3we9zl_x5jE5FyL_vxx1RievYRUvc](url)

This is the installation debug file

**Comment by swapnilkamble3924** [comment]
is it workings fine for 32bit now?
